platform :ios, '12.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
end

# Post install script to ensure Flutter frameworks are included
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end