name: Complete iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-complete:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        cache: true
        
    - name: Setup CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup
        
    - name: Clean and prepare
      run: |
        flutter clean
        flutter pub get
        
    - name: Generate Flutter iOS files
      run: |
        flutter precache --ios
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update --verbose
        cd ..
        
    - name: Build iOS for eSign (Release)
      run: |
        flutter build ios --release --no-codesign --no-pub --no-tree-shake-icons --verbose
        
    - name: Create IPA for eSign
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        cp -r Runner.app Payload/
        zip -r ../../../PPAPIKey_Mobile_Complete.ipa Payload/
        cd ../../..
        
    - name: Upload IPA for eSign
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-complete-for-esign
        path: PPAPIKey_Mobile_Complete.ipa
        retention-days: 30

    - name: Build iOS for Device (Debug)
      run: |
        flutter build ios --debug --no-pub --no-tree-shake-icons --verbose
        
    - name: Create IPA for Device
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        cp -r Runner.app Payload/
        zip -r ../../../PPAPIKey_Mobile_Device.ipa Payload/
        cd ../../..
        
    - name: Upload IPA for Device
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-complete-for-device
        path: PPAPIKey_Mobile_Device.ipa
        retention-days: 30
