name: Build IPA for iOS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        cache: true
        
    - name: Build iOS App
      run: |
        echo "=== BUILDING iOS APP ==="
        flutter pub get
        flutter build ios --release --no-codesign
        
        echo "=== CREATING IPA ==="
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../ppapikey.ipa Payload/
        rm -rf Payload
        
        echo "=== BUILD COMPLETED ==="
        ls -lh ../../../ppapikey.ipa
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ppapikey-ipa
        path: ppapikey.ipa
        retention-days: 30