name: iOS Build - Fixed

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        cache: true
        
    - name: Setup CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup
        
    - name: Clean project
      run: |
        flutter clean
        rm -rf ios/Pods
        rm -rf ios/Podfile.lock
        
    - name: Get dependencies
      run: |
        flutter pub get
        
    - name: Generate Flutter iOS files
      run: |
        flutter precache --ios
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        cd ..
        
    - name: Build iOS for eSign
      run: |
        flutter build ios --release --no-codesign --no-pub --no-tree-shake-icons
        
    - name: Create IPA for eSign
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        cp -r Runner.app Payload/
        zip -r ../../../PPAPIKey_Mobile_Fixed.ipa Payload/
        cd ../../..
        
    - name: Upload IPA for eSign
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-fixed-for-esign
        path: PPAPIKey_Mobile_Fixed.ipa
        retention-days: 30
